/**
 * Email validation types — EveryBuilding Tier 2
 *
 * Every generated email is validated before being pushed to Instantly.
 * A failed validation triggers one corrective retry with an amended prompt.
 * If the retry also fails, the email is logged and skipped for this cycle.
 *
 * Validation checks:
 *   - Hard violations (must retry): word count, missing building reference, CTA mismatch
 *   - Soft violations (warn only): tone flags, phrase violations
 */

import type { CtaNumber, CtaName } from "./cta";

// ─── The generated email structure ───────────────────────────────────────────

/**
 * The parsed output from Claude Haiku before validation.
 * The LLM is expected to return a structured JSON object matching this shape.
 */
export interface GeneratedEmail {
  subject: string;
  /** Full email body text (excludes subject, signature line, sender sign-off) */
  body: string;
  /**
   * The Company Signature Line — one sentence between body and sender name.
   * Generated by the LLM using the resolved SignatureLineData.
   */
  signature_line: string;
  /** Sender sign-off first name (from SenderIdentity.sender_sign_off_name) */
  sender_sign_off: string;
  /** Full sender name (from SenderIdentity.sender_full_name) */
  sender_full_name: string;
  /** Sender title (from SenderIdentity.sender_title) */
  sender_title: string;
  /** Computed at validation time — word count of body only (excludes subject + signature) */
  word_count: number;
  /** CTA number the LLM reports it used (cross-checked against the requested cta_number) */
  cta_number_used: CtaNumber;
  cta_name_used: CtaName;
}

// ─── Validation rule ──────────────────────────────────────────────────────────

export type ValidationSeverity =
  | "hard"  // MUST retry — email cannot be sent with this violation
  | "soft"; // Log and warn — email can be sent but issue is flagged

export interface EmailValidationRule {
  rule_id: string;
  description: string;
  severity: ValidationSeverity;
}

// ─── Validation result ────────────────────────────────────────────────────────

export interface EmailValidationViolation {
  rule_id: string;
  description: string;
  severity: ValidationSeverity;
}

export interface EmailValidationResult {
  /** true only if zero hard violations (soft violations still pass) */
  passed: boolean;
  violations: EmailValidationViolation[];
  word_count: number;
  /**
   * If there are hard violations, this is a targeted corrective prompt
   * appended to the next LLM attempt explaining what needs to change.
   * null if passed (or soft violations only).
   */
  retry_prompt: string | null;
  validated_at: string; // ISO timestamp
}

// ─── The built-in validation rule set ────────────────────────────────────────

/**
 * The standard rules applied to every generated email.
 * These are the defaults; individual CTA entries can declare additional rules
 * via their `rules` array, which the validator handles as soft checks.
 */
export const STANDARD_VALIDATION_RULES: EmailValidationRule[] = [
  {
    rule_id: "word_limit",
    description: "Email body must be under 100 words",
    severity: "hard",
  },
  {
    rule_id: "building_referenced",
    description: "Email body must reference the building address or a specific building detail",
    severity: "hard",
  },
  {
    rule_id: "cta_number_match",
    description: "The CTA type used in the email must match the requested CTA number",
    severity: "hard",
  },
  {
    rule_id: "no_links_in_body",
    description: "Unless the CTA explicitly allows a link, no URLs may appear in the email body",
    severity: "hard",
  },
  {
    rule_id: "real_sender",
    description: "Email must be signed from a real person name — no generic AI persona names",
    severity: "hard",
  },
  {
    rule_id: "no_forbidden_phrase_just",
    description: 'Email must not contain the word "just" (e.g. "just wanted to")',
    severity: "soft",
  },
  {
    rule_id: "no_ai_opener",
    description: 'Email must not open with AI-sounding phrases like "I hope this email finds you well"',
    severity: "soft",
  },
  {
    rule_id: "signature_line_present",
    description: "Email must include a Company Signature Line between body and sender sign-off",
    severity: "hard",
  },
];

// ─── Retry context ────────────────────────────────────────────────────────────

/**
 * Passed back to the composer when a retry is needed.
 * The composer appends the corrective_instruction to the next user prompt.
 */
export interface ValidationRetryContext {
  attempt_number: 2; // only ever 2 — one retry max
  original_violations: EmailValidationViolation[];
  corrective_instruction: string;
}
